repos:
  - repo: https://github.com/mdevino/pre-commit-rust
    rev: v1.2
    hooks:
      - id: fmt-nightly
        args: ["--all"]
      - id: cargo-check
      - id: clippy
        args: ["--workspace", "--all-features"]