language: minimal
rust:
  - 1.77.2
vm: 
  size: 2x-large
services:
  - docker
cache: cargo
if: branch = main OR type = pull_request
env:
  global:
    - REGISTRY_SERVER=us.icr.io
    - REGISTRY_NAMESPACE=cil15-shared-registry
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/detectors
    - PROTOC_VERSION=3.19.6
    - SHORT_IMAGE_NAME=fms-guardrails-orchestr8
before_install: 
      - sudo apt update && sudo apt install -y build-essential 
      - PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
      - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.6/$PROTOC_ZIP
      - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
      - sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
      - rm -f $PROTOC_ZIP
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
      - chmod +x ./rust-init.sh
      - ./rust-init.sh --yes
      - git clone https://github.com/foundation-model-stack/fms-guardrails-orchestrator.git orchestrator
      - cd orchestrator
install: cargo install --path .
before_deploy:
      - LONG_IMAGE_NAME=${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${SHORT_IMAGE_NAME}:${TRAVIS_COMMIT:0:7}
      - docker build -qt $LONG_IMAGE_NAME -t latest .
      - echo "${REGISTRY_PASSWORD}" | docker login --username ${REGISTRY_USERNAME} --password-stdin ${REGISTRY_SERVER}
deploy:
  - provider: script
    skip_cleanup: true
    script: docker push --all-tags ${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${SHORT_IMAGE_NAME}:latest
    on:
      branch: main
