language: rust
rust:
  - 1.77.2
vm: 
  size: 2x-large
services:
  - docker
cache: cargo
if: branch = main OR type = pull_request
env:
  global:
    - REGISTRY_SERVER=us.icr.io
    - REGISTRY_NAMESPACE=cil15-shared-registry
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/detectors
    - PROTOC_VERSION=3.19.6
    - SHORT_IMAGE_NAME=fms-guardrails-orchestr8
before_install: 
      - sudo apt update && sudo apt install -y build-essential
      - PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
      - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.6/$PROTOC_ZIP
      - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
      - sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
      - rm -f $PROTOC_ZIP
install: cargo install --path .
before_deploy:
      - LONG_IMAGE_NAME=${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${SHORT_IMAGE_NAME}:${TRAVIS_COMMIT:0:7}
      - echo "${REGISTRY_PASSWORD}" | docker login --username ${REGISTRY_USERNAME} --password-stdin ${REGISTRY_SERVER}
      - docker build -t LONG_IMAGE_NAME .
      # - docker push ${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${SHORT_IMAGE_NAME}:latest
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Yay!"
    on:
      branch: main
