generation:
  provider: tgis
  service:
    hostname: localhost
    port: 8034
chunkers:
  sentence_syntax_izumo_en_stock_chunker:
    type: sentence
    service:
      hostname: localhost
      port: 8085
detectors:
  en_syntax_rbr_pii:
    service:
      hostname: https://brl-pii-fmaas-tuning.apps.fmaas-devstage-backend.fmaas.res.ibm.com/api/v1/text/contents
      port: 443
    chunker_id: sentence_syntax_izumo_en_stock_chunker
    default_threshold: 0.8
  en_syntax_slate.38m.hap:
    service:
      hostname: https://brl-hap-fmaas-tuning.apps.fmaas-devstage-backend.fmaas.res.ibm.com/api/v1/text/contents
      port: 443
    chunker_id: sentence_syntax_izumo_en_stock_chunker
    default_threshold: 0.5
  en_syntax_slate_38m_hap:
    service:
      hostname: https://brl-hap-fmaas-tuning.apps.fmaas-devstage-backend.fmaas.res.ibm.com/api/v1/text/contents
      port: 443
    chunker_id: sentence_syntax_izumo_en_stock_chunker
    default_threshold: 0.5
tls: {}